'use strict';
// Patch feature gates — computes globalThis.__clawgodPatches before the
// patched cli loads. Config: user-edited ~/.clawgod/patches.json
// ({"<feature>": false}, absent key = on). CLAWGOD_FEATURES env
// ("feature=false,other=true") overrides per launch. CLAWGOD_FEATURES_META
// below is machine-generated by build.js from the FEATURES registry in
// patch.mjs (single source of truth) — do not hand-edit. Each gated patch in
// cli.original.cjs checks its own entry:
//   globalThis.__clawgodPatches?.["<patchId>"] !== false
// Absent/failed config → gate table absent → all gates default ON, which is
// exactly the pre-toggle behavior.
// {{CLAWGOD:FEATURES_META}}

var clawgodDir = require('path').join(require('os').homedir(), '.clawgod');

var _cfg = {};
try { _cfg = JSON.parse(require('fs').readFileSync(require('path').join(clawgodDir, 'patches.json'), 'utf8')); } catch {}
var _env = process.env.CLAWGOD_FEATURES;
if (_env) {
  var _items = _env.split(',');
  for (var _i = 0; _i < _items.length; _i++) {
    var _m = _items[_i].trim().match(/^([\w-]+)=(true|false)$/);
    if (_m) _cfg[_m[1]] = _m[2] === 'true';
  }
}

// META keys are patch ids; a feature id is "known" when some patch lists it.
// Unknown keys are residue (renamed/removed features).
for (var _k in _cfg) {
  var _known = false;
  for (var _f in CLAWGOD_FEATURES_META) {
    if (CLAWGOD_FEATURES_META[_f].indexOf(_k) >= 0) { _known = true; break; }
  }
  if (!_known) process.stderr.write('[clawgod] warning: unknown feature "' + _k + '" in patches.json\n');
}

var _gate = {};
for (var _pid in CLAWGOD_FEATURES_META) {
  var _feats = CLAWGOD_FEATURES_META[_pid];
  var _on = false;
  for (var _j = 0; _j < _feats.length; _j++) {
    if (_cfg[_feats[_j]] !== false) { _on = true; break; }
  }
  _gate[_pid] = _on;
}
globalThis.__clawgodPatches = _gate;
